[package]
name = "coreforge-gui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true
camino.workspace = true
rfd.workspace = true

coreforge-core.workspace = true
scheduler.workspace = true
executor.workspace = true
config.workspace = true

[lints]
workspace = true
