[package]
name = "coreforge-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
camino.workspace = true
tracing.workspace = true
indicatif.workspace = true

executor.workspace = true
scheduler.workspace = true
coreforge-core.workspace = true
toolchain.workspace = true
logging.workspace = true
collector.workspace = true
config.workspace = true
