name: Documentation

on:
    push:
        branches:
            - main

    pull_request:

    workflow_dispatch:

permissions:
    contents: read

jobs:
    docs:
        name: Build & Validate Documentation

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Cache Cargo
              uses: Swatinem/rust-cache@v2

            - name: Install mdBook
              run: cargo install --locked mdbook

            - name: Install mdBook Linkcheck
              run: cargo install --locked mdbook-linkcheck

            - name: Install Lychee
              uses: lycheeverse/lychee-action@v2
              with:
                  version: latest

            - name: Install html5validator
              run: |
                  python3 -m pip install --upgrade pip
                  pip install html5validator

            - name: Install CSpell
              run: npm install -g cspell

            - name: Build documentation
              run: mdbook build docs

            - name: Check internal links
              run: mdbook test docs

            - name: Check external links
              run: |
                  lychee \
                    --verbose \
                    --no-progress \
                    docs/src/**/*.md

            - name: Validate HTML
              run: html5validator --root docs/book

            - name: Spell check
              run: |
                  cspell \
                    "docs/src/**/*.md"
