name: Documentation

on:
    push:
        branches:
            - main

    pull_request:

    workflow_dispatch:

permissions:
    contents: read

jobs:
    docs:
        name: Build & Validate Documentation

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Cache Cargo
              uses: Swatinem/rust-cache@v2

            - name: Install mdBook
              run: cargo install --locked mdbook

            - name: Install Lychee
              run: cargo install --locked lychee

            - name: Install CSpell
              run: npm install -g cspell

            - name: Install MarkdownLint
              run: npm install -g markdownlint-cli2

            - name: Build documentation
              run: mdbook build docs

            - name: Test Rust examples
              run: mdbook test docs

            - name: Lint Markdown
              run: markdownlint-cli2 "docs/src/**/*.md"

            - name: Check links
              run: |
                  lychee \
                    --verbose \
                    --no-progress \
                    docs/src/**/*.md

            - name: Spell check
              run: |
                  cspell \
                    "docs/src/**/*.md"
